USE master;
GO

CREATE DATABASE MovieCatalogue;
GO

USE MovieCatalogue;
GO

CREATE TABLE Movie(
MovieID INT IDENTITY (1,1) PRIMARY KEY,
GenreID INT FOREIGN KEY REFERENCES Genre(GenreID) NOT NULL,
DirectorID INT FOREIGN KEY REFERENCES Director(DirectorID) NOT NULL,
RatingID INT FOREIGN KEY REFERENCES Rating(RatingID) NOT NULL,
Title NVARCHAR(128) NOT NULL,
[Release Date] DATE NULL
)
GO

CREATE TABLE Genre(
GenreID	INT IDENTITY (1,1) PRIMARY KEY,
GenreName NVARCHAR(30) NOT NULL
)
GO

CREATE TABLE Director(
DirectorID INT IDENTITY (1,1) PRIMARY KEY,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR (30) NOT NULL,
BirthDate DATE NULL
)
GO

CREATE TABLE Rating(
RatingID INT IDENTITY (1,1) PRIMARY KEY,
RatingName VARCHAR (5)
)
GO

CREATE TABLE Actor(
ActorID INT IDENTITY (1,1) PRIMARY KEY,
FirstName NVARCHAR (30) NOT NULL,
LastName NVARCHAR(30) NOT NULL,
BirthDate DATE NULL
)
GO

CREATE TABLE CastMembers(
CastMemberID INT IDENTITY (1,1) PRIMARY KEY,
ActorID INT FOREIGN KEY REFERENCES Actor(ActorID) NOT NULL,
MovieID INT FOREIGN KEY REFERENCES Movie(MovieID) NOT NULL,
[Role] NVARCHAR (50) NOT NULL
)
GO