// <auto-generated />
namespace Movie_Catalog_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class directorAndYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(directorAndYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201610051713510_directorAndYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
